### PR TITLE
Setting feature

### PR DESCRIPTION
**Pull request by Ohior**
I couldn't get pass this error `A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xa0 in tid 5413 (GLThread 66), pid 3757 (nderfootandroid)`. I don't really know why, but when I redesign the drawer, the error stopped. I think it had to do with database.
I added a setting feature to the, with just 1 item, I can add more items or remove that feature

### CODE REVIEW

**Review by kueda — CHANGES_REQUESTED** [review]
Hey @Ohior. I appreciate the effort, but there are a number of blockers here. The most accute one is is that trying to follow the repro steps in #3 results in the following crash when attempting to navigate from Rocks to Downloads:

```
FATAL EXCEPTION: main
Process: rocks.underfoot.underfootandroid, PID: 28586
java.lang.IllegalStateException: no current navigation node
  at androidx.navigation.NavController.navigate(NavController.kt:1498)
  at androidx.navigation.NavController.navigate(NavController.kt:1468)
  at androidx.navigation.NavController.navigate(NavController.kt:1926)
  at rocks.underfoot.underfootandroid.rocks.RocksFragment.navigateToDownloads(RocksFragment.kt:24)
  at rocks.underfoot.underfootandroid.maptuils.MapFragment.setupMap$lambda-2$lambda-1(MapFragment.kt:74)
  at rocks.underfoot.underfootandroid.maptuils.MapFragment.$r8$lambda$tFvZzF89sEqNFw3KN03PzBu8ULw(Unknown Source:0)
  at rocks.underfoot.underfootandroid.maptuils.MapFragment$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
  at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
  at android.os.Handler.dispatchMessage(Handler.java:106)
  at android.os.Looper.loopOnce(Looper.java:201)
  at android.os.Looper.loop(Looper.java:288)
  at android.app.ActivityThread.main(ActivityThread.java:7842)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

That's running Android 12 on a Pixel 3.

More generally, there are the following blockers:

1. #3 concerns a specific bug and does not concern adding a Settings screen. I might want Settings screen eventually, but that would be a subject for a separate issue
2. This app tries to follow a single activity architecture as [recommended by Google](https://developer.android.com/topic/architecture/recommendations#ui-layer), so I don't think an additional Settings activity would be required even if that was a part of the scope of work here.

**Comment by Ohior** [comment]
I run pixel 3 API 31 and I don't have that error. my navigation is quite smooth. Try to invalidate caches and rebuild the app.
The error I do come in contact with is `A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xa0 in tid 22176 (GLThread 78), pid 22011 (nderfootandroid)`

**Comment by kueda** [comment]
Yup, I cleaned the build and invalidated caches and I get exactly the same error on my Pixel 3, and when running a Pixel 3 / API 31 emulator.

**Comment by Ohior** [comment]
What lead to this error?. I do not seem to get this error when I run the app and navigate rock and download fragment.
Try making download the home fragment, or I can help you build up the whole project from scratch.

**Comment by kueda** [comment]
I don't know what causes the error, but it happens consistently, after cleaning and invalidating caches, on device and in an emulator, whether the default fragments is rocks or water.

**Comment by Ohior** [comment]
> I don't know what causes the error, but it happens consistently, after cleaning and invalidating caches, on device and in an emulator, whether the default fragments is rocks or water.

I have a few fix. But since I do not get the error, that means that the error is at your end.
1. I think the error is in your fragment navigation, the fragment API you are using do not know how to navigate to that fragment.
2. What I think you should do is move the project to another folder and upgrade your android studio, and gradle. then create another project. now you can just copy paste your previous code to your new project. By consistently testing each stages of this new project you might find where the error is.
3. You mentioned something about following `Google recommended practice `. Then you should use jetpack compose. Since this is the future of mobile app development (because of KMM).
I hope theses options help, because I do not get the error when I run the app on my emulator
my emulator is {
`Android studio dolphin`
`Pixel 4 API 31`
`gradle version 7.4`
}

**Comment by kueda** [comment]
Fair enough. Thanks for the advice!

**Pull request closed without merging**
